### ISSUE TITLE
Ship timezones

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar-js#273]
The time zones data for the time zone manager are provided by the code that uses this lib. This was perfectly fine when the lib was only used in Calendar. Now for the time zone picker in `@nextcloud/vue` I copied the code/data over to use it there. For the time zone picker in Mail I realize that I will actually need to get hold off a time zone manager loaded with the data. So I'd have to copy the logic and data a second time. This is starting to smell and I think we should probably just include the tz data here in this lib and use a primed tz manager in the apps/libs.

cc @tcitworld just in case you know why the tz data was added to calendar instead of here when the tz manager was added :)

**Comment by tcitworld** [comment]
It could be related to the fact that we truncate the timezone data to close years (see `HISTORY_CUTOFF`), it might not be appropriate for some uses & apps. Some applications may also want a lighter or restricted list of timezones. :shrug: 

But yeah, moving the data and the `getSortedTimezoneList` and the `getReadableTimezoneName` functions here would be nice.

We should also update it (see the python script) when moving it btw.

**Comment by ChristophWurst** [comment]
> We should also update it (see the python script) when moving it btw.

Absolutely. Wasn't able to do so yet, though.

``` 
Downloading tzdata-latest.tar.gz from ftp.iana.org to /tmp/zonesBC6ZKf.tar.gz
Extracting /tmp/zonesBC6ZKf.tar.gz to /tmp/zonesgybDvw
You are using tzdata 2021a
Exporting pure zone info to /tmp/zonesVHw6bk
/tmp/zonesgybDvw/africa:1092: Strange year: 2039
Rule    Morocco 2039    only    -       Sep     18       3:00   -1:00   -

Traceback (most recent call last):
  File "update-zones.py", line 418, in <module>
    main()
  File "update-zones.py", line 412, in main
    updater.run(json_file, tzprops_file, args.vzic_path)
  File "update-zones.py", line 318, in run
    self.run_vzic(vzic_path)
  File "update-zones.py", line 72, in run_vzic
    ], stdout=sys.stderr)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/....../tzurl/vzic/vzic-fork/vzic', '--olson-dir', '/tmp/zonesgybDvw', '--output-dir', '/tmp/zonesVHw6bk', '--pure']' returned non-zero exit status 1
```

**Comment by tcitworld** [comment]
> Strange year: 2039

Is that https://en.wikipedia.org/wiki/Year_2038_problem ?

**Comment by ChristophWurst** [comment]
Yep most likely. I'm trying to figure out why my Python (both v2 and v3) don't like >2038

**Comment by tcitworld** [comment]
I have a different set of issues :tada: 
<details>

```
Downloading tzdata-latest.tar.gz from ftp.iana.org to /tmp/zonesjwgdi2t_.tar.gz  
Extracting /tmp/zonesjwgdi2t_.tar.gz to /tmp/zonesdt_silkk  
You are using tzdata 2021a  
Exporting pure zone info to /tmp/zones7pyz45p7  
Zone description not found for: CET
Zone description not found for: CST6CDT
Zone description not found for: EET
Zone description not found for: EST
Zone description not found for: EST5EDT
Zone description not found for: Etc/GMT
Zone description not found for: Etc/GMT+1
Zone description not found for: Etc/GMT+10
Zone description not found for: Etc/GMT+11
Zone description not found for: Etc/GMT+12
Zone description not found for: Etc/GMT+2
Zone description not found for: Etc/GMT+3
Zone description not found for: Etc/GMT+4
Zone description not found for: Etc/GMT+5
Zone description not found for: Etc/GMT+6
Zone description not found for: Etc/GMT+7
Zone description not found for: Etc/GMT+8
Zone description not found for: Etc/GMT+9
Zone description not found for: Etc/GMT-1
Zone description not found for: Etc/GMT-10
Zone description not found for: Etc/GMT-11
Zone description not found for: Etc/GMT-12
Zone description not found for: Etc/GMT-13
Zone description not found for: Etc/GMT-14
Zone description not found for: Etc/GMT-2
Zone description not found for: Etc/GMT-3
Zone description not found for: Etc/GMT-4
Zone description not found for: Etc/GMT-5
Zone description not found for: Etc/GMT-6
Zone description not found for: Etc/GMT-7
Zone description not found for: Etc/GMT-8
Zone description not found for: Etc/GMT-9
Zone description not found for: Etc/UTC
Zone description not found for: HST
Zone description not found for: MET
Zone description not found for: MST
Zone description not found for: MST7MDT
Zone description not found for: PST8PDT
Zone description not found for: WET
Line in zones.tab not long enough: CET
Line in zones.tab not long enough: CST6CDT
Line in zones.tab not long enough: EET
Line in zones.tab not long enough: EST
Line in zones.tab not long enough: EST5EDT
Line in zones.tab not long enough: Etc/GMT
Line in zones.tab not long enough: Etc/GMT+1
Line in zones.tab not long enough: Etc/GMT+10
Line in zones.tab not long enough: Etc/GMT+11
Line in zones.tab not long enough: Etc/GMT+12
Line in zones.tab not long enough: Etc/GMT+2
Line in zones.tab not long enough: Etc/GMT+3
Line in zones.tab not long enough: Etc/GMT+4
Line in zones.tab not long enough: Etc/GMT+5
Line in zones.tab not long enough: Etc/GMT+6
Line in zones.tab not long enough: Etc/GMT+7
Line in zones.tab not long enough: Etc/GMT+8
Line in zones.tab not long enough: Etc/GMT+9
Line in zones.tab not long enough: Etc/GMT-1
Line in zones.tab not long enough: Etc/GMT-10
Line in zones.tab not long enough: Etc/GMT-11
Line in zones.tab not long enough: Etc/GMT-12
Line in zones.tab not long enough: Etc/GMT-13
Line in zones.tab not long enough: Etc/GMT-14
Line in zones.tab not long enough: Etc/GMT-2
Line in zones.tab not long enough: Etc/GMT-3
Line in zones.tab not long enough: Etc/GMT-4
Line in zones.tab not long enough: Etc/GMT-5
Line in zones.tab not long enough: Etc/GMT-6
Line in zones.tab not long enough: Etc/GMT-7
Line in zones.tab not long enough: Etc/GMT-8
Line in zones.tab not long enough: Etc/GMT-9
Line in zones.tab not long enough: Etc/UTC
Line in zones.tab not long enough: HST
Line in zones.tab not long enough: MET
Line in zones.tab not long enough: MST
Line in zones.tab not long enough: MST7MDT
Line in zones.tab not long enough: PST8PDT
Line in zones.tab not long enough: WET
Traceback (most recent call last):
  File "/home/tcit/dev/nextcloud/server/apps/calendar/timezones/./update-zones.py", line 418, in <module>
    main()
  File "/home/tcit/dev/nextcloud/server/apps/calendar/timezones/./update-zones.py", line 412, in main
    updater.run(json_file, tzprops_file, args.vzic_path)
  File "/home/tcit/dev/nextcloud/server/apps/calendar/timezones/./update-zones.py", line 321, in run
    newzones = self.read_dir(self.zoneinfo_pure_path,
  File "/home/tcit/dev/nextcloud/server/apps/calendar/timezones/./update-zones.py", line 248, in read_dir
    zones.update(self.read_dir(fullpath, process_zone, os.path.join(prefix, entry)))
  File "/home/tcit/dev/nextcloud/server/apps/calendar/timezones/./update-zones.py", line 251, in read_dir
    zones[filename[:-4]] = process_zone(filename)
  File "/home/tcit/dev/nextcloud/server/apps/calendar/timezones/./update-zones.py", line 322, in <lambda>
    lambda fn: self.read_ics(fn, lat_long_data))
  File "/home/tcit/dev/nextcloud/server/apps/calendar/timezones/./update-zones.py", line 166, in read_ics
    if not last and "valid_rdates" in component and len(component["valid_rdates"]) > 0:
TypeError: object of type 'filter' has no len()
```

</details>

**Comment by tcitworld** [comment]
Wouldn't it be `vzic` that has issues in your case?

**Comment by ChristophWurst** [comment]
I've used https://github.com/benfortuna/tzurl/tree/develop/vzic/vzic-fork

**Comment by ChristophWurst** [comment]
Same result with the original https://sourceforge.net/projects/vzic/

**Comment by tcitworld** [comment]
This one seems to be more official & up-to-date https://github.com/libical/vzic/
